apiVersion: v1
kind: PersistentVolume
metadata:
  name: localstack-data-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/tmp/localstack/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localstack-data-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
spec:
  selector:
    matchLabels:
      run: localstack
  replicas: 1
  template:
    metadata:
      labels:
        run: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:0.12.17
          env:
            - name: SERVICES
              value: "dynamodb,kinesis,cloudwatch"
            - name: DATA_DIR
              value: "/tmp/localstack/data"
            - name: KINESIS_INITIALIZE_STREAMS
              value: "teststream:1"
            - name: LS_LOG
              value: "warn"
            - name: KINESIS_SHARD_LIMIT
              value: "1"
            - name: AWS_CBOR_DISABLE
              value: "true"
          ports:
            - containerPort: 4566
          volumeMounts:
            - mountPath: /tmp/localstack
              name: localstack-data-volume
      volumes:
        - name: localstack-data-volume
          persistentVolumeClaim:
            claimName: localstack-data-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  labels:
    run: localstack
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4566
      targetPort: 4566
      nodePort: 30000
  selector:
    run: localstack
