apiVersion: v1
kind: Pod
metadata:
  name: localstack
spec:
  containers:
    - image: localstack/localstack:0.12.17
      name: localstack
      env:
        - name: SERVICES
          value: "dynamodb,kinesis,cloudwatch"
        - name: DATA_DIR
          value: "/tmp/localstack/data"
        - name: KINESIS_INITIALIZE_STREAMS
          value: "teststream:1"
        - name: LS_LOG
          value: "warn"
        - name: KINESIS_SHARD_LIMIT
          value: "1"
        - name: AWS_CBOR_DISABLE
          value: "true"

      ports:
        - containerPort: 4566
          hostPort: 4566

      volumeMounts:
        - mountPath: /tmp/localstack
          name: localstack-data-volume
  volumes:
    - name: localstack-data-volume
      persistentVolumeClaim:
        claimName: localstack-data-volume-claim