server:
  port: 8081


management:
  endpoints:
    web:
      base-path: /private
      exposure.include: info

app:
  kinesisUri: http://localhost:30000
  streamName: teststream
  accessKey: test
  secretAccessKey: test

