version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:0.12.17
    network_mode: bridge
    ports:
      - "127.0.0.1:4566:4566"
    environment:
      - SERVICES=dynamodb,kinesis,cloudwatch
      - DATA_DIR=/tmp/localstack/data
      - KINESIS_INITIALIZE_STREAMS=teststream:1
      - LS_LOG=warn
      - KINESIS_SHARD_LIMIT=1
      - AWS_CBOR_DISABLE=true

    volumes:
      - "/tmp/localstack/data:/tmp/localstack"
