/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.consumer;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration;
import org.springframework.context.annotation.Import;

@SpringBootApplication(exclude = {ContextInstanceDataAutoConfiguration.class})
@Import({org.springframework.cloud.stream.binder.kinesis.config.KinesisBinderConfiguration.class})
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}
